import type { DocsLocale } from "./locales";

const english = {
    common: {
        save: "Save",
        saving: "Saving…",
        cancel: "Cancel",
        delete: "Delete",
        keep: "Keep it",
        edit: "Edit",
        add: "Add",
        none: "None",
        saved: "Saved.",
        status: { draft: "Draft", published: "Published", archived: "Archived" }
    },
    shell: {
        navigation: {
            content: "Content",
            configuration: "Configuration",
            overview: "Overview",
            posts: "Posts",
            pages: "Pages",
            taxonomy: "Taxonomy",
            media: "Media",
            design: "Design",
            roles: "Roles",
            storage: "Storage",
            settings: "Settings"
        },
        theme: { light: "Light", dark: "Dark", system: "System", change: "Change theme" },
        account: { open: "Account", signOut: "Sign out" },
        locale: { choose: "Choose interface language", unsupported: "That interface Locale is not supported." },
        breadcrumb: { new: "New", revisions: "Revisions" },
        overview: {
            title: "Overview",
            description: "Manage content, presentation, permissions and publishing infrastructure from one place."
        }
    },
    auth: {
        login: {
            title: "Sign in",
            description: (siteTitle: string) => `Continue to the ${siteTitle} admin.`,
            email: "Email",
            password: "Password",
            submit: "Sign in",
            submitting: "Signing in…",
            required: "Enter your email address and password.",
            invalid: "That email address and password do not match an account."
        },
        setup: {
            title: "Set up",
            readyTitle: "Set up this site",
            blockedTitle: "Almost ready",
            readyDescription: "This site has no accounts yet. Once one exists, this page closes for good.",
            blockedDescription: "A few things are not in place yet. Each one says what to do about it.",
            siteTitle: "Site title",
            siteTitleDescription: "Change this later under Settings.",
            name: "Name",
            email: "Email",
            password: "Password",
            passwordDescription: "At least eight characters.",
            submit: "Create administrator",
            submitting: "Creating…",
            required: "Fill in every field to finish setting the site up.",
            rejected: "The administrator account could not be created. Check the account details and try again.",
            requirements: {
                databaseName: "The database has had its migrations applied",
                databaseRemedy: "Run: pnpm db:migrate (add --remote for the deployed database).",
                bucketName: (label: string, binding: string) => `The bucket “${label}” is bound as ${binding}`,
                bucketRemedy: (binding: string, bucketName: string) =>
                    `Add an r2_buckets entry binding ${binding} to ${bucketName} in wrangler.jsonc.`,
                signingName: "A signing secret is configured",
                signingRemedy:
                    "Set BETTER_AUTH_SECRET to at least 32 characters. Generate one with: openssl rand -base64 32",
                addressName: "The address this site is served from is known",
                addressRemedy: "Set BETTER_AUTH_URL to the address readers use, such as https://example.com."
            }
        }
    },
    editor: {
        collection: { none: "None", toggleUnset: "Not set", toggleYes: "Yes", toggleNo: "No" },
        richText: {
            toolbar: "Formatting",
            placeholder: "Write…",
            undo: "Undo",
            redo: "Redo",
            heading: "Heading",
            bold: "Bold",
            italic: "Italic",
            strike: "Strike",
            inlineCode: "Inline code",
            bulletList: "Bullet list",
            numberedList: "Numbered list",
            quote: "Quote",
            link: "Link",
            removeLink: "Remove link",
            linkAddress: "Link address",
            media: "Media",
            insertMedia: "Insert Media",
            insertMediaDescription: "Select an image already managed by the platform or store a new one.",
            storeImage: "Store image",
            storingImage: "Storing…",
            readingMedia: "Reading Media…",
            noImages: "No images have been stored yet.",
            mediaUnavailable: "The Media library could not be read.",
            imageUploadFailed: "The image could not be stored.",
            imageAlternative: "Image description",
            imageAlternativePlaceholder: "Describe what the image communicates",
            decorativeImage: "This image is decorative",
            insertImage: "Insert image",
            imageAlternativeRequired: "Describe the image or mark it as decorative.",
            close: "Close"
        },
        blocks: {
            addBlock: "Add a Block",
            moveUp: "Move up",
            moveDown: "Move down",
            remove: "Remove",
            empty: "No Blocks yet.",
            unknown: "Unknown Block"
        }
    },
    posts: {
        list: {
            title: "Posts",
            count: (count: number) => (count === 1 ? "One Post" : `${count} Posts`),
            new: "New Post",
            permission: "You do not have permission to read Posts.",
            emptyTitle: "Nothing written yet.",
            emptyCreate: "Create the first Post to see it here.",
            emptyWait: "Posts will appear here once they exist.",
            titleColumn: "Title",
            statusColumn: "Status",
            viewsColumn: "Views",
            lastEditedColumn: "Last edited",
            views: (count: number) => `${count} views`,
            lastEdited: (moment: string) => `Last edited ${moment}`
        },
        form: {
            newTitle: "New Post",
            editTitle: "Edit Post",
            permissionCreate: "You do not have permission to write Posts.",
            permissionUpdate: "You do not have permission to edit this Post.",
            untitled: "Untitled",
            slug: "Slug",
            slugPlaceholder: "Taken from the title",
            slugDescription: (pattern: string) =>
                `Leave this empty and the title decides. Public addresses follow ${pattern}.`,
            addressDescription: (pattern: string) => `Public addresses follow ${pattern}.`,
            category: "Category",
            selectCategory: "Select a Category",
            categoryRequired: "Create a Category before saving a Post.",
            tags: "Tags",
            noTags: "No Tags are available yet.",
            bodyPlaceholder: "Write the Post body…",
            richTextBlockPlaceholder: "Write this Rich Text Block…",
            status: "Status",
            save: "Save Post",
            revisions: "Revisions",
            preview: "Preview"
        },
        preview: {
            title: "Post preview",
            back: "Edit Post",
            status: {
                draft: "Draft preview saved",
                archived: "Archived preview saved",
                published: "Published preview saved"
            }
        },
        delete: {
            title: (title: string) => `Delete “${title}”?`,
            description:
                "The Post and everything in it goes for good. To take it out of sight without losing it, archive it instead."
        },
        revisions: {
            title: "Revisions",
            count: (count: number) => (count === 1 ? "One saved state" : `${count} saved states`),
            back: "Back to Post",
            empty: "No Revisions have been saved yet.",
            slug: "Slug",
            saved: "Saved",
            savedAt: (moment: string) => `Saved ${moment}`,
            detailSavedAt: (moment: string) => `Revision saved ${moment}`,
            all: "All Revisions",
            savedState: "Saved state",
            status: "Status",
            category: "Category",
            published: "Published",
            notPublished: "Not published",
            tags: "Tags",
            noTags: "No Tags",
            deletedCategory: (id: string) => `Deleted Category (${id})`,
            deletedTag: (id: string) => `Deleted Tag (${id})`,
            restore: "Restore this Revision",
            restoring: "Restoring…"
        },
        errors: {
            invalidBody: "The Post body is not valid rich text.",
            required: "A Post needs a title and a body.",
            invalidField: "One of the Post fields is not valid.",
            selectCategory: "Select a category.",
            missing: "That Post no longer exists.",
            writeDenied: "You do not have permission to write this Post.",
            taxonomyDenied: "You do not have permission to assign Taxonomy.",
            categoryMissing: "The selected Category no longer exists.",
            tagMissing: "One of the selected Tags no longer exists.",
            publishDenied: "You may write this Post, but not change whether it is published.",
            deleteDenied: "You do not have permission to delete this Post.",
            revisionUnavailable: "That Revision is not available.",
            revisionRestoreFailed: "That Revision could not be restored."
        }
    },
    pages: {
        list: {
            title: "Pages",
            description:
                "Pages are built from components and addressed by their own path. “/” replaces the default home listing.",
            new: "New Page",
            permission: "You do not have permission to read Pages.",
            emptyTitle: "No Pages yet.",
            emptyCreate: "Create a home page, a portfolio, or anything else composed of Blocks.",
            emptyWait: "Pages will appear here once they exist.",
            blocks: (count: number) => (count === 1 ? "One Block" : `${count} Blocks`)
        },
        form: {
            newTitle: "New Page",
            newDescription: "Start from an empty body, or add a Heading and a Paragraph and grow from there.",
            editTitle: "Edit Page",
            permissionCreate: "You do not have permission to create Pages.",
            permissionUpdate: "You do not have permission to update Pages.",
            viewOnSite: "View on site",
            create: "Create Page",
            save: "Save Page",
            title: "Title",
            address: "Address",
            status: "Status",
            blocks: "Blocks",
            empty: "No Blocks yet. Add the first one below.",
            addBlock: "Add a Block",
            dragBlock: (index: number) => `Drag Block ${index}`,
            savedLive: "Saved. Published changes are live on the site."
        },
        errors: {
            permission: {
                create: "You do not have permission to create Pages.",
                update: "You do not have permission to update Pages.",
                delete: "You do not have permission to delete Pages.",
                publish: "You do not have permission to publish Pages."
            },
            bodyProblems: (details: string) => `The body has problems: ${details}`,
            bodyInvalid: "The Page body is invalid.",
            bodyUnreadable: "The body could not be read.",
            createFailed: "The Page could not be created.",
            saveFailed: "The Page could not be saved.",
            titleRequired: "A Page needs a title.",
            addressStart: "A Page address has to start with “/”.",
            addressEnd: "A Page address cannot end with “/”.",
            addressDoubleSlash: "A Page address cannot contain “//”.",
            addressExists: (address: string) => `A Page at “${address}” already exists.`,
            missing: "No such Page.",
            readBack: "The Page could not be read back."
        }
    },
    taxonomy: {
        title: "Taxonomy",
        description: "Organise Posts with hierarchical Categories and flat Tags.",
        permission: "You do not have permission to manage Taxonomy.",
        categories: "Categories",
        categoriesDescription: "Hierarchical. Every Post belongs to exactly one.",
        tags: "Tags",
        tagsDescription: "Flat labels. A Post may use any number of them.",
        name: "Name",
        slug: "Slug",
        slugDescription: "Leave empty to derive it from the name.",
        parent: "Parent",
        noParent: "No parent",
        saveCategory: "Save Category",
        addCategory: "Add Category",
        saveTag: "Save Tag",
        addTag: "Add Tag",
        errors: {
            saveFailed: "Taxonomy could not be saved.",
            slugUsed: "That slug is already in use.",
            assigned: "This term is still assigned and cannot be removed.",
            termRequired: "A Taxonomy term needs a name or Slug that produces an address.",
            ownDescendant: "A Category cannot become its own descendant.",
            cycle: "The existing Category hierarchy contains a cycle.",
            parentMissing: "The parent Category does not exist.",
            categoryName: "A Category needs a name.",
            categoryReadBack: "The Category was saved but could not be read back.",
            categoryMissing: "That Category does not exist.",
            childrenFirst: "Move or remove this Category’s children first.",
            tagName: "A Tag needs a name.",
            tagReadBack: "The Tag was saved but could not be read back.",
            tagMissing: "That Tag does not exist."
        }
    },
    media: {
        title: "Media",
        count: (count: number) => (count === 1 ? "One file" : `${count} files`),
        permission: "You do not have permission to see Media.",
        empty: "Nothing uploaded yet.",
        drop: "Drop files here",
        limit: (megabytes: number) => `Up to ${megabytes} MB each.`,
        choose: "Choose files",
        preparing: "preparing…",
        sending: (progress?: number) => (progress === undefined ? "sending…" : `sending ${progress}%`),
        confirming: "confirming…",
        stored: "stored",
        uploadFailed: "The upload failed.",
        unavailable: "The Media library could not be read.",
        deleteTitle: (filename: string) => `Delete “${filename}”?`,
        deleteDescription:
            "The file goes from storage for good. Anywhere it has been placed in a Post will be left pointing at nothing.",
        deleteDenied: "You do not have permission to delete this file."
    },
    design: {
        title: "Design",
        description:
            "The accent colours every interactive surface. More of the theme becomes adjustable as the design system grows.",
        permission: "You do not have permission to see the design.",
        presets: "Presets",
        presetNames: {
            inkBlue: "Ink Blue",
            deepIndigo: "Deep Indigo",
            forest: "Forest",
            teal: "Teal",
            clay: "Clay",
            rose: "Rose"
        },
        custom: "Custom colour",
        apply: "Apply",
        customDescription:
            "Any CSS colour works. Text on top of it is kept legible automatically, and the whole Site updates the moment it is applied.",
        applied: "Accent applied across the Site.",
        permissionManage: "You do not have permission to change the design.",
        saveFailed: "That accent could not be saved.",
        invalid: "That does not look like a colour."
    },
    roles: {
        title: "Roles",
        description: "Choose what each system Role may do. Capability changes apply to every user holding that Role.",
        permission: "You do not have permission to see Role capabilities.",
        noRoles: "No system Roles are installed.",
        systemRole: "System Role",
        manageAccess: "Manage access",
        readOnly: "Read only",
        capabilities: (resource: string) => `${resource} capabilities`,
        recovery: "Locked so an Administrator can always inspect and repair Role capabilities.",
        saved: "Role capabilities saved.",
        save: "Save Role capabilities",
        permissionManage: "You do not have permission to change Role capabilities.",
        saveFailed: "Those Role capabilities could not be saved.",
        roleLabels: {
            admin: "Administrator",
            editor: "Editor",
            author: "Author",
            contributor: "Contributor",
            subscriber: "Subscriber"
        },
        roleDescriptions: {
            admin: "Full control, including Site settings and user management.",
            editor: "Publishes and manages content from any author.",
            author: "Publishes and manages their own content.",
            contributor: "Writes their own content but cannot publish it.",
            subscriber: "Reads content and takes part in discussion."
        },
        resources: {
            comment: "Comments",
            media: "Media",
            page: "Pages",
            post: "Posts",
            role: "Roles",
            session: "Sessions",
            settings: "Settings",
            taxonomy: "Taxonomy",
            user: "Users"
        },
        actions: {
            "create": "Create",
            "read": "Read",
            "list": "List",
            "get": "Get",
            "update": "Update",
            "delete": "Delete",
            "manage": "Manage",
            "moderate": "Moderate",
            "publish": "Publish",
            "upload": "Upload",
            "revoke": "Revoke",
            "ban": "Ban",
            "update-own": "Update own",
            "delete-own": "Delete own",
            "publish-own": "Publish own",
            "update-any": "Update any",
            "delete-any": "Delete any",
            "publish-any": "Publish any",
            "set-role": "Set Role",
            "set-password": "Set password"
        }
    },
    settings: {
        title: "Settings",
        permission: "You do not have permission to see settings.",
        groups: { site: "Site", format: "Dates and times", permalink: "Addresses", media: "Media" },
        preview: (value: string) => `Shows as ${value}`,
        save: "Save settings",
        permissionManage: "You do not have permission to change settings.",
        numberRequired: (label: string) => `${label} needs to be a number.`,
        saveFailed: "Those settings could not be saved.",
        fields: {
            "site.title": { label: "Site title" },
            "site.description": { label: "Tagline" },
            "format.date": { label: "Date format", description: "Patterns follow date-fns, such as yyyy-MM-dd." },
            "format.time": { label: "Time format" },
            "media.maxUploadMegabytes": {
                label: "Largest upload",
                description:
                    "In megabytes. A file that arrives through the server is also bounded by the platform it runs on."
            },
            "permalink.post": { label: "Posts address" }
        },
        errors: {
            patternRequired: "Give a pattern, such as yyyy-MM-dd.",
            patternInvalid: "That date or time pattern cannot be used.",
            addressStart: "An address starts with a slash.",
            addressSegments: "An address is made of non-empty path segments.",
            addressQuery: "An address pattern cannot contain a query string or fragment.",
            addressTokenSegment: "A token has to occupy a complete path segment, such as /{year}/{slug}.",
            addressUnknownToken: "That address contains an unknown token.",
            addressSlug: "The address must include {slug}, or every Entry would live at the same one.",
            uploadLimit: "An upload limit has to be more than nothing.",
            invalidSetting: (key: string) => `The value for ${key} is not valid.`
        }
    },
    storage: {
        title: "Storage",
        description: "Buckets describe reachable storage. Ordered rules decide where each new file lands.",
        permission: "You do not have permission to see storage settings.",
        fallback: {
            title: "Fallback destination",
            description: "This catches every upload no earlier rule claims. It cannot be removed.",
            missing: "The fallback rule is missing. Uploads may fail.",
            select: "Fallback bucket",
            set: "Set fallback"
        },
        buckets: {
            title: "Buckets",
            count: (count: number) => (count === 1 ? "One destination" : `${count} destinations`),
            add: "Add bucket",
            addTitle: "Add an R2 bucket",
            addDescription: "The deployment binding must exist before it can be registered here.",
            editTitle: (label: string) => `Edit ${label}`,
            editDescription: "Rename the destination or change how stored files are served.",
            location: "Location",
            use: "Use",
            status: "Status",
            actions: "Actions",
            bucket: "Bucket",
            reachable: "Reachable",
            unavailable: "Unavailable",
            fallback: "Fallback",
            usage: (media: number, rules: number) => `${media} Media · ${rules} rules`,
            credentialsNote:
                "External S3-compatible credentials are deliberately not editable here until Jamcaa can seal them at rest.",
            id: "Bucket ID",
            idDescription: "Stable and lowercase. Media and rules keep this ID, so it cannot be renamed later.",
            name: "Name",
            namePlaceholder: "Site media",
            binding: "R2 binding",
            bindingDescription: "The binding must already exist in wrangler.jsonc and this deployment.",
            cloudflareName: "Cloudflare bucket name",
            cloudflareDescription: "Required later if the browser will upload directly with a signed address.",
            notConfigured: "Not configured",
            locationDescription:
                "Deployment bindings and physical bucket names stay in code so existing Media cannot be disconnected accidentally.",
            publicAddress: "Public address",
            publicDescription: "Optional. Without one, Jamcaa securely streams the file through its own Media route.",
            addSubmit: "Add bucket",
            saveSubmit: "Save bucket",
            blockedByRules: "Move or delete every rule that uses this bucket first.",
            blockedByMedia: "This bucket still holds Media."
        },
        rules: {
            title: "Routing rules",
            description: "First matching rule wins. The fallback always runs last.",
            add: "Add rule",
            addTitle: "Add a routing rule",
            addDescription: "Choose a destination and describe which uploads it claims.",
            emptyTitle: "No routing rules",
            emptyDescription: "Every upload currently goes to the fallback destination.",
            safeDefault: "Safe default",
            priority: (priority: number) => `Priority ${priority}`,
            conditions: "Conditions",
            destination: "Destination",
            order: "Order",
            rule: "Rule",
            actions: "Actions",
            moveUp: "Move rule up",
            moveDown: "Move rule down",
            editTitle: (label: string) => `Edit ${label}`,
            editDescription: "Existing Media stays where it is; this changes future uploads only.",
            damaged: "Damaged conditions — this rule is skipped",
            everyUpload: "Every upload",
            collection: (values: string) => `collection: ${values}`,
            category: (values: string) => `category: ${values}`,
            tag: (values: string) => `tag: ${values}`,
            role: (values: string) => `role: ${values}`,
            authorIds: (count: number) => `${count} author ID${count === 1 ? "" : "s"}`,
            type: (values: string) => `type: ${values}`,
            atLeast: (size: string) => `at least ${size}`,
            atMost: (size: string) => `at most ${size}`,
            from: (date: string) => `from ${date}`,
            until: (date: string) => `until ${date}`,
            name: "Name",
            namePlaceholder: "Large videos",
            destinationBucket: "Destination bucket",
            matchDescription:
                "Every filled condition must match. Leave all conditions empty only when this rule should claim every upload before the fallback.",
            damagedDescription: "This rule has damaged conditions. Saving will replace them.",
            fileTypes: "File types",
            fileTypesDescription: "Comma separated MIME types or prefixes. For example, image/ matches every image.",
            minimum: "Minimum MB",
            maximum: "Maximum MB",
            more: "More conditions",
            collections: "Collections",
            categories: "Categories",
            tags: "Tags",
            authorRoles: "Author Roles",
            authorIdsLabel: "Author IDs",
            authorIdsPlaceholder: "One user ID per line",
            fromLabel: "From",
            untilLabel: "Until",
            addSubmit: "Add rule",
            saveSubmit: "Save rule"
        },
        delete: {
            title: (label: string) => `Delete “${label}”?`,
            bucketDescription:
                "Only an unused bucket can be removed. Its deployment binding and Cloudflare bucket remain untouched.",
            ruleDescription:
                "Future uploads will no longer be routed by this rule. Existing files stay where they are.",
            deleting: "Deleting…"
        },
        close: "Close",
        errors: {
            "changeDenied": "You do not have permission to change storage.",
            "changeFailed": "Storage could not be changed.",
            "bucket-exists": "A bucket with that ID already exists.",
            "bucket-in-use": "Move its rules and Media before deleting this bucket.",
            "bucket-not-found": "That bucket no longer exists.",
            "binding-unavailable": "This deployment does not expose that R2 binding.",
            "fallback-rule-protected": "The fallback rule is protected.",
            "invalid-bucket": "The bucket details are not valid.",
            "invalid-conditions": "The rule conditions are not valid.",
            "invalid-order": "The rule order changed elsewhere. Reload the page and try again.",
            "invalid-rule": "The rule details are not valid.",
            "rule-not-found": "That storage rule no longer exists."
        }
    }
} as const;

type WidenCopy<T> =
    T extends (...arguments_: infer TArguments) => infer TResult ? (...arguments_: TArguments) => TResult
    : T extends string ? string
    : T extends readonly unknown[] ? { [TIndex in keyof T]: WidenCopy<T[TIndex]> }
    : T extends object ? { [TKey in keyof T]: WidenCopy<T[TKey]> }
    : T;

export type AdminCopy = WidenCopy<typeof english>;

const simplifiedChinese = {
    common: {
        save: "保存",
        saving: "保存中…",
        cancel: "取消",
        delete: "删除",
        keep: "保留",
        edit: "编辑",
        add: "添加",
        none: "无",
        saved: "已保存。",
        status: { draft: "草稿", published: "已发布", archived: "已归档" }
    },
    shell: {
        navigation: {
            content: "内容",
            configuration: "配置",
            overview: "概览",
            posts: "文章",
            pages: "页面",
            taxonomy: "分类法",
            media: "媒体",
            design: "设计",
            roles: "角色",
            storage: "存储",
            settings: "设置"
        },
        theme: { light: "浅色", dark: "深色", system: "跟随系统", change: "切换主题" },
        account: { open: "账户", signOut: "退出登录" },
        locale: { choose: "选择界面语言", unsupported: "不支持此界面语言。" },
        breadcrumb: { new: "新建", revisions: "修订记录" },
        overview: { title: "概览", description: "在一个地方管理内容、呈现、权限与发布基础设施。" }
    },
    auth: {
        login: {
            title: "登录",
            description: (siteTitle: string) => `继续进入 ${siteTitle} 管理后台。`,
            email: "邮箱",
            password: "密码",
            submit: "登录",
            submitting: "登录中…",
            required: "请输入邮箱和密码。",
            invalid: "邮箱或密码与账户不匹配。"
        },
        setup: {
            title: "初始化",
            readyTitle: "初始化站点",
            blockedTitle: "即将就绪",
            readyDescription: "此站点还没有账户。首个账户创建后，本页面将永久关闭。",
            blockedDescription: "部署仍缺少少量必要配置；每一项都附有处理方法。",
            siteTitle: "站点标题",
            siteTitleDescription: "稍后可在“设置”中修改。",
            name: "姓名",
            email: "邮箱",
            password: "密码",
            passwordDescription: "至少 8 个字符。",
            submit: "创建管理员",
            submitting: "创建中…",
            required: "请填写所有字段以完成站点初始化。",
            rejected: "无法创建管理员账户。请检查账户信息后重试。",
            requirements: {
                databaseName: "数据库迁移已应用",
                databaseRemedy: "运行：pnpm db:migrate（部署环境的数据库请添加 --remote）。",
                bucketName: (label: string, binding: string) => `Bucket“${label}”已绑定为 ${binding}`,
                bucketRemedy: (binding: string, bucketName: string) =>
                    `在 wrangler.jsonc 的 r2_buckets 中添加绑定 ${binding}，指向 ${bucketName}。`,
                signingName: "已配置签名密钥",
                signingRemedy: "将 BETTER_AUTH_SECRET 设置为至少 32 个字符。可运行 openssl rand -base64 32 生成。",
                addressName: "已配置站点公开地址",
                addressRemedy: "将 BETTER_AUTH_URL 设置为读者访问的地址，例如 https://example.com。"
            }
        }
    },
    editor: {
        collection: { none: "无", toggleUnset: "未设置", toggleYes: "是", toggleNo: "否" },
        richText: {
            toolbar: "格式",
            placeholder: "开始写作…",
            undo: "撤销",
            redo: "重做",
            heading: "标题",
            bold: "粗体",
            italic: "斜体",
            strike: "删除线",
            inlineCode: "行内代码",
            bulletList: "项目符号列表",
            numberedList: "编号列表",
            quote: "引用",
            link: "链接",
            removeLink: "移除链接",
            linkAddress: "链接地址",
            media: "媒体",
            insertMedia: "插入媒体",
            insertMediaDescription: "选择平台已管理的图片，或上传一张新图片。",
            storeImage: "上传图片",
            storingImage: "上传中…",
            readingMedia: "正在读取媒体…",
            noImages: "尚未上传图片。",
            mediaUnavailable: "无法读取媒体库。",
            imageUploadFailed: "无法上传图片。",
            imageAlternative: "图片说明",
            imageAlternativePlaceholder: "描述图片传达的内容",
            decorativeImage: "这是一张装饰性图片",
            insertImage: "插入图片",
            imageAlternativeRequired: "请描述图片，或将其标记为装饰性图片。",
            close: "关闭"
        },
        blocks: {
            addBlock: "添加 Block",
            moveUp: "上移",
            moveDown: "下移",
            remove: "移除",
            empty: "尚无 Blocks。",
            unknown: "未知 Block"
        }
    },
    posts: {
        list: {
            title: "文章",
            count: (count: number) => `${count} 篇文章`,
            new: "新建文章",
            permission: "你没有查看文章的权限。",
            emptyTitle: "还没有文章。",
            emptyCreate: "创建第一篇文章后，它会显示在这里。",
            emptyWait: "文章创建后会显示在这里。",
            titleColumn: "标题",
            statusColumn: "状态",
            viewsColumn: "浏览量",
            lastEditedColumn: "最后编辑",
            views: (count: number) => `${count} 次浏览`,
            lastEdited: (moment: string) => `最后编辑于 ${moment}`
        },
        form: {
            newTitle: "新建文章",
            editTitle: "编辑文章",
            permissionCreate: "你没有撰写文章的权限。",
            permissionUpdate: "你没有编辑这篇文章的权限。",
            untitled: "未命名",
            slug: "Slug",
            slugPlaceholder: "根据标题生成",
            slugDescription: (pattern: string) => `留空时将根据标题决定。公开地址遵循 ${pattern}。`,
            addressDescription: (pattern: string) => `公开地址遵循 ${pattern}。`,
            category: "分类",
            selectCategory: "选择分类",
            categoryRequired: "保存文章前请先创建分类。",
            tags: "标签",
            noTags: "尚无可用标签。",
            bodyPlaceholder: "撰写文章正文…",
            richTextBlockPlaceholder: "撰写这个富文本 Block…",
            status: "状态",
            save: "保存文章",
            revisions: "修订记录",
            preview: "预览"
        },
        preview: {
            title: "文章预览",
            back: "编辑文章",
            status: { draft: "草稿预览已保存", archived: "归档预览已保存", published: "已发布版本预览已保存" }
        },
        delete: {
            title: (title: string) => `删除“${title}”？`,
            description: "文章及其全部内容将被永久删除。如只想暂时隐藏且保留内容，请改为归档。"
        },
        revisions: {
            title: "修订记录",
            count: (count: number) => `${count} 个已保存状态`,
            back: "返回文章",
            empty: "尚未保存修订记录。",
            slug: "Slug",
            saved: "保存时间",
            savedAt: (moment: string) => `保存于 ${moment}`,
            detailSavedAt: (moment: string) => `修订记录保存于 ${moment}`,
            all: "全部修订记录",
            savedState: "已保存状态",
            status: "状态",
            category: "分类",
            published: "发布时间",
            notPublished: "未发布",
            tags: "标签",
            noTags: "无标签",
            deletedCategory: (id: string) => `已删除的分类（${id}）`,
            deletedTag: (id: string) => `已删除的标签（${id}）`,
            restore: "恢复此修订记录",
            restoring: "恢复中…"
        },
        errors: {
            invalidBody: "文章正文不是有效的富文本。",
            required: "文章需要标题和正文。",
            invalidField: "文章中有字段无效。",
            selectCategory: "请选择分类。",
            missing: "这篇文章已不存在。",
            writeDenied: "你没有撰写这篇文章的权限。",
            taxonomyDenied: "你没有分配分类法的权限。",
            categoryMissing: "所选分类已不存在。",
            tagMissing: "所选标签中有一项已不存在。",
            publishDenied: "你可以编辑这篇文章，但不能更改其发布状态。",
            deleteDenied: "你没有删除这篇文章的权限。",
            revisionUnavailable: "此修订记录不可用。",
            revisionRestoreFailed: "无法恢复此修订记录。"
        }
    },
    pages: {
        list: {
            title: "页面",
            description: "页面由组件构成，并拥有独立路径。“/”会替换默认首页内容列表。",
            new: "新建页面",
            permission: "你没有查看页面的权限。",
            emptyTitle: "还没有页面。",
            emptyCreate: "创建首页、作品集，或任何由 Blocks 组合而成的页面。",
            emptyWait: "页面创建后会显示在这里。",
            blocks: (count: number) => `${count} 个 Block`
        },
        form: {
            newTitle: "新建页面",
            newDescription: "从空白正文开始，或先添加标题和段落，再逐步扩展。",
            editTitle: "编辑页面",
            permissionCreate: "你没有创建页面的权限。",
            permissionUpdate: "你没有更新页面的权限。",
            viewOnSite: "在站点中查看",
            create: "创建页面",
            save: "保存页面",
            title: "标题",
            address: "地址",
            status: "状态",
            blocks: "Blocks",
            empty: "尚无 Blocks。请在下方添加第一个。",
            addBlock: "添加 Block",
            dragBlock: (index: number) => `拖动第 ${index} 个 Block`,
            savedLive: "已保存。已发布的更改现已在站点生效。"
        },
        errors: {
            permission: {
                create: "你没有创建页面的权限。",
                update: "你没有更新页面的权限。",
                delete: "你没有删除页面的权限。",
                publish: "你没有发布页面的权限。"
            },
            bodyProblems: (details: string) => `正文存在问题：${details}`,
            bodyInvalid: "页面正文无效。",
            bodyUnreadable: "无法读取正文。",
            createFailed: "无法创建页面。",
            saveFailed: "无法保存页面。",
            titleRequired: "页面需要标题。",
            addressStart: "页面地址必须以“/”开头。",
            addressEnd: "页面地址不能以“/”结尾。",
            addressDoubleSlash: "页面地址不能包含“//”。",
            addressExists: (address: string) => `地址“${address}”已有页面。`,
            missing: "页面不存在。",
            readBack: "无法重新读取页面。"
        }
    },
    taxonomy: {
        title: "分类法",
        description: "使用层级分类和扁平标签组织文章。",
        permission: "你没有管理分类法的权限。",
        categories: "分类",
        categoriesDescription: "支持层级结构；每篇文章必须属于一个分类。",
        tags: "标签",
        tagsDescription: "扁平标签；每篇文章可以使用任意数量的标签。",
        name: "名称",
        slug: "Slug",
        slugDescription: "留空时将根据名称生成。",
        parent: "上级分类",
        noParent: "无上级分类",
        saveCategory: "保存分类",
        addCategory: "添加分类",
        saveTag: "保存标签",
        addTag: "添加标签",
        errors: {
            saveFailed: "无法保存分类法。",
            slugUsed: "此 Slug 已被使用。",
            assigned: "此项目仍在使用中，无法删除。",
            termRequired: "分类法项目需要名称，或需要能生成地址的 Slug。",
            ownDescendant: "分类不能成为自身的后代。",
            cycle: "现有分类层级中存在循环。",
            parentMissing: "上级分类不存在。",
            categoryName: "分类需要名称。",
            categoryReadBack: "分类已保存，但无法重新读取。",
            categoryMissing: "此分类不存在。",
            childrenFirst: "请先移动或删除此分类的子分类。",
            tagName: "标签需要名称。",
            tagReadBack: "标签已保存，但无法重新读取。",
            tagMissing: "此标签不存在。"
        }
    },
    media: {
        title: "媒体",
        count: (count: number) => `${count} 个文件`,
        permission: "你没有查看媒体的权限。",
        empty: "尚未上传文件。",
        drop: "将文件拖到这里",
        limit: (megabytes: number) => `每个文件最大 ${megabytes} MB。`,
        choose: "选择文件",
        preparing: "准备中…",
        sending: (progress?: number) => (progress === undefined ? "上传中…" : `上传中 ${progress}%`),
        confirming: "确认中…",
        stored: "已存储",
        uploadFailed: "上传失败。",
        unavailable: "无法读取媒体库。",
        deleteTitle: (filename: string) => `删除“${filename}”？`,
        deleteDescription: "文件将从存储中永久删除。文章中使用此文件的位置将无法再显示内容。",
        deleteDenied: "你没有删除此文件的权限。"
    },
    design: {
        title: "设计",
        description: "强调色用于所有可交互界面。随着设计系统完善，更多主题选项也会开放调整。",
        permission: "你没有查看设计设置的权限。",
        presets: "预设",
        presetNames: {
            inkBlue: "墨蓝",
            deepIndigo: "深靛蓝",
            forest: "森林绿",
            teal: "青绿",
            clay: "陶土",
            rose: "玫瑰"
        },
        custom: "自定义颜色",
        apply: "应用",
        customDescription: "支持任何 CSS 颜色。系统会自动保持文字可读性，应用后整个站点立即更新。",
        applied: "强调色已应用到整个站点。",
        permissionManage: "你没有更改设计的权限。",
        saveFailed: "无法保存此强调色。",
        invalid: "这不是有效的颜色。"
    },
    roles: {
        title: "角色",
        description: "设置每个系统角色可以执行的操作。能力变更会应用到所有拥有该角色的用户。",
        permission: "你没有查看角色能力的权限。",
        noRoles: "尚未安装系统角色。",
        systemRole: "系统角色",
        manageAccess: "可管理",
        readOnly: "只读",
        capabilities: (resource: string) => `${resource}能力`,
        recovery: "此能力已锁定，确保管理员始终可以检查并修复角色能力。",
        saved: "角色能力已保存。",
        save: "保存角色能力",
        permissionManage: "你没有更改角色能力的权限。",
        saveFailed: "无法保存这些角色能力。",
        roleLabels: { admin: "管理员", editor: "编辑", author: "作者", contributor: "投稿者", subscriber: "订阅者" },
        roleDescriptions: {
            admin: "拥有完整控制权，包括站点设置和用户管理。",
            editor: "可发布并管理任意作者的内容。",
            author: "可发布并管理自己的内容。",
            contributor: "可撰写自己的内容，但不能发布。",
            subscriber: "可阅读内容并参与讨论。"
        },
        resources: {
            comment: "评论",
            media: "媒体",
            page: "页面",
            post: "文章",
            role: "角色",
            session: "会话",
            settings: "设置",
            taxonomy: "分类法",
            user: "用户"
        },
        actions: {
            "create": "创建",
            "read": "读取",
            "list": "列出",
            "get": "查看",
            "update": "更新",
            "delete": "删除",
            "manage": "管理",
            "moderate": "审核",
            "publish": "发布",
            "upload": "上传",
            "revoke": "撤销",
            "ban": "封禁",
            "update-own": "更新自己的内容",
            "delete-own": "删除自己的内容",
            "publish-own": "发布自己的内容",
            "update-any": "更新任意内容",
            "delete-any": "删除任意内容",
            "publish-any": "发布任意内容",
            "set-role": "设置角色",
            "set-password": "设置密码"
        }
    },
    settings: {
        title: "设置",
        permission: "你没有查看设置的权限。",
        groups: { site: "站点", format: "日期与时间", permalink: "地址", media: "媒体" },
        preview: (value: string) => `显示为 ${value}`,
        save: "保存设置",
        permissionManage: "你没有更改设置的权限。",
        numberRequired: (label: string) => `${label}必须是数字。`,
        saveFailed: "无法保存这些设置。",
        fields: {
            "site.title": { label: "站点标题" },
            "site.description": { label: "标语" },
            "format.date": { label: "日期格式", description: "格式遵循 date-fns，例如 yyyy-MM-dd。" },
            "format.time": { label: "时间格式" },
            "media.maxUploadMegabytes": {
                label: "最大上传大小",
                description: "单位为 MB。经服务器上传的文件还会受到运行平台限制。"
            },
            "permalink.post": { label: "文章地址" }
        },
        errors: {
            patternRequired: "请输入格式，例如 yyyy-MM-dd。",
            patternInvalid: "此日期或时间格式无法使用。",
            addressStart: "地址必须以斜杠开头。",
            addressSegments: "地址必须由非空路径段组成。",
            addressQuery: "地址格式不能包含查询参数或片段。",
            addressTokenSegment: "Token 必须独占一个完整路径段，例如 /{year}/{slug}。",
            addressUnknownToken: "地址中包含未知 Token。",
            addressSlug: "地址必须包含 {slug}，否则所有内容都会使用同一个地址。",
            uploadLimit: "上传大小限制必须大于零。",
            invalidSetting: (key: string) => `${key} 的值无效。`
        }
    },
    storage: {
        title: "存储",
        description: "Bucket 描述可访问的存储；按顺序执行的规则决定每个新文件的存放位置。",
        permission: "你没有查看存储设置的权限。",
        fallback: {
            title: "兜底目标",
            description: "所有未被前序规则接收的上传都会进入这里，且此规则不能删除。",
            missing: "兜底规则缺失，上传可能失败。",
            select: "兜底 Bucket",
            set: "设置兜底目标"
        },
        buckets: {
            title: "Buckets",
            count: (count: number) => `${count} 个目标`,
            add: "添加 Bucket",
            addTitle: "添加 R2 Bucket",
            addDescription: "部署绑定必须已存在，才能在这里注册。",
            editTitle: (label: string) => `编辑 ${label}`,
            editDescription: "重命名目标，或更改已存储文件的访问方式。",
            location: "位置",
            use: "使用情况",
            status: "状态",
            actions: "操作",
            bucket: "Bucket",
            reachable: "可访问",
            unavailable: "不可用",
            fallback: "兜底",
            usage: (media: number, rules: number) => `${media} 个媒体 · ${rules} 条规则`,
            credentialsNote: "在 Jamcaa 能够安全加密保存凭据前，这里不会开放外部 S3 兼容凭据编辑。",
            id: "Bucket ID",
            idDescription: "必须稳定且使用小写。媒体和规则会引用此 ID，后续不能重命名。",
            name: "名称",
            namePlaceholder: "站点媒体",
            binding: "R2 绑定",
            bindingDescription: "绑定必须已存在于 wrangler.jsonc 和当前部署中。",
            cloudflareName: "Cloudflare Bucket 名称",
            cloudflareDescription: "浏览器未来通过签名地址直接上传时需要此项。",
            notConfigured: "未配置",
            locationDescription: "部署绑定和物理 Bucket 名保留在代码中，避免现有媒体被意外断开。",
            publicAddress: "公开地址",
            publicDescription: "可选。留空时，Jamcaa 会通过自身媒体路由安全传输文件。",
            addSubmit: "添加 Bucket",
            saveSubmit: "保存 Bucket",
            blockedByRules: "请先移动或删除所有使用此 Bucket 的规则。",
            blockedByMedia: "此 Bucket 中仍有媒体。"
        },
        rules: {
            title: "路由规则",
            description: "首条匹配规则生效；兜底规则始终最后执行。",
            add: "添加规则",
            addTitle: "添加路由规则",
            addDescription: "选择目标，并描述它要接收哪些上传。",
            emptyTitle: "没有路由规则",
            emptyDescription: "当前所有上传都会进入兜底目标。",
            safeDefault: "安全默认值",
            priority: (priority: number) => `优先级 ${priority}`,
            conditions: "条件",
            destination: "目标",
            order: "顺序",
            rule: "规则",
            actions: "操作",
            moveUp: "上移规则",
            moveDown: "下移规则",
            editTitle: (label: string) => `编辑 ${label}`,
            editDescription: "现有媒体位置不变；此修改只影响未来上传。",
            damaged: "条件已损坏——此规则将被跳过",
            everyUpload: "所有上传",
            collection: (values: string) => `Collection：${values}`,
            category: (values: string) => `分类：${values}`,
            tag: (values: string) => `标签：${values}`,
            role: (values: string) => `角色：${values}`,
            authorIds: (count: number) => `${count} 个作者 ID`,
            type: (values: string) => `类型：${values}`,
            atLeast: (size: string) => `至少 ${size}`,
            atMost: (size: string) => `至多 ${size}`,
            from: (date: string) => `从 ${date}`,
            until: (date: string) => `至 ${date}`,
            name: "名称",
            namePlaceholder: "大型视频",
            destinationBucket: "目标 Bucket",
            matchDescription: "所有已填写条件都必须匹配。仅当此规则要在兜底前接收所有上传时，才将条件全部留空。",
            damagedDescription: "此规则的条件已损坏；保存会用当前表单内容替换它们。",
            fileTypes: "文件类型",
            fileTypesDescription: "使用逗号分隔 MIME 类型或前缀，例如 image/ 可匹配所有图片。",
            minimum: "最小 MB",
            maximum: "最大 MB",
            more: "更多条件",
            collections: "Collections",
            categories: "分类",
            tags: "标签",
            authorRoles: "作者角色",
            authorIdsLabel: "作者 ID",
            authorIdsPlaceholder: "每行一个用户 ID",
            fromLabel: "开始日期",
            untilLabel: "结束日期",
            addSubmit: "添加规则",
            saveSubmit: "保存规则"
        },
        delete: {
            title: (label: string) => `删除“${label}”？`,
            bucketDescription: "只有未使用的 Bucket 才能删除。部署绑定和 Cloudflare Bucket 不会受到影响。",
            ruleDescription: "未来上传将不再经过此规则；现有文件仍保留在原位置。",
            deleting: "删除中…"
        },
        close: "关闭",
        errors: {
            "changeDenied": "你没有更改存储的权限。",
            "changeFailed": "无法更改存储配置。",
            "bucket-exists": "已有相同 ID 的 Bucket。",
            "bucket-in-use": "删除此 Bucket 前，请先移动其中的规则和媒体。",
            "bucket-not-found": "此 Bucket 已不存在。",
            "binding-unavailable": "当前部署未暴露该 R2 绑定。",
            "fallback-rule-protected": "兜底规则受到保护。",
            "invalid-bucket": "Bucket 信息无效。",
            "invalid-conditions": "规则条件无效。",
            "invalid-order": "规则顺序已在其他位置改变，请刷新页面后重试。",
            "invalid-rule": "规则信息无效。",
            "rule-not-found": "此存储规则已不存在。"
        }
    }
} satisfies AdminCopy;

const copies = { "en-US": english, "zh-Hans-CN": simplifiedChinese } satisfies Record<DocsLocale, AdminCopy>;

export function adminCopy(locale: DocsLocale): AdminCopy {
    return copies[locale];
}
