import type { DocsLocale } from "./locales";

const copy = {
    "en-US": {
        languageName: "English",
        skipToContent: "Skip to content",
        navigationLabel: "Primary navigation",
        docs: "Docs",
        guides: "Guides",
        reference: "Reference",
        changelog: "Changelog",
        search: "Search",
        dashboard: "Dashboard",
        openMenu: "Open navigation",
        closeMenu: "Close navigation",
        switchLanguage: "Choose language",
        theme: { light: "Light", dark: "Dark", system: "System", change: "Change theme" },
        languageChooserDetail: "Documentation, guides, reference and changelog",
        onThisPage: "On this page",
        previous: "Previous",
        next: "Next",
        editPage: "Edit this page",
        updated: "Updated",
        homeEyebrow: "Pre-alpha · Schema-driven publishing for Cloudflare Workers",
        homeTitle: "Define the model once. Keep publishing contracts aligned.",
        homeDescription:
            "Declare Collections and Fields in TypeScript. Jamcaa derives D1 storage, validation, Editing Controls, typed Entry access, Entry Summaries, Revisions and FTS5 migration artifacts. Your Site keeps its routes and rendering.",
        getStarted: "Run the reference Site",
        exploreDocs: "Explore the docs",
        builtWithJamcaa: "This Site uses Jamcaa's own Page, Entry Summary, Search, Feed, Preview and Revision paths.",
        architectureEyebrow: "Derived contracts · Explicit boundaries",
        architectureTitle: "One declaration. Clear Site ownership.",
        architectureDescription:
            "Collection declarations drive storage, validation, typed access, Entry Summaries, Revision codecs and Search artifacts. Pages, routes and Block views stay explicit; browser Editing Controls live in the optional Editor package.",
        latestTitle: "Latest published documentation",
        latestDescription:
            "The newest published Post summaries for this Locale, read through the same cursor-based projection used by archives and JSON Feed.",
        noPosts: "No documentation entries are published in this language yet.",
        allPostsLoaded: "All documentation entries loaded.",
        category: "Category",
        tag: "Tag",
        categoryEmpty: "No documentation entries belong directly to this category.",
        tagEmpty: "No documentation entries use this tag.",
        searchTitle: "Search the documentation",
        searchDescription: "Search declared public text, then narrow results by category or tag.",
        searchTerms: "Search terms",
        searchPlaceholder: "Search Jamcaa Docs",
        allCategories: "All categories",
        allTags: "All tags",
        clear: "Clear",
        resultsFor: "Results for",
        noResults: "No documentation entries match this search.",
        enterSearch: "Enter one or more terms to search the documentation.",
        invalidSearchCursor: "This result page address is invalid or has expired. Start the search again.",
        nextPage: "Next page",
        loading: "Loading…",
        loadingAnnouncement: "Loading the next page.",
        loadedAnnouncement: (count: number, complete: boolean) =>
            complete ?
                count === 0 ?
                    "All documentation entries loaded."
                :   `${count} more ${count === 1 ? "entry" : "entries"} loaded. All documentation entries loaded.`
            :   `${count} more ${count === 1 ? "entry" : "entries"} loaded.`,
        loadError: "The next page could not load automatically.",
        loadErrorAnnouncement: "The next page could not load automatically. Retry or use the Next page link.",
        retry: "Retry",
        retrying: "Retrying…",
        pageLoaded: "Page loaded",
        notTranslatedTitle: "This page is not translated yet.",
        notTranslatedDescription: "Continue in the available language or return to this language's documentation home.",
        returnHome: "Return to docs home",
        notFoundTitle: "Page not found",
        notFoundDescription: "The address may have changed, or the page may not exist on this Site.",
        goHome: "Go home"
    },
    "zh-Hans-CN": {
        languageName: "简体中文",
        skipToContent: "跳到正文",
        navigationLabel: "主导航",
        docs: "文档",
        guides: "教程",
        reference: "参考",
        changelog: "更新日志",
        search: "搜索",
        dashboard: "控制台",
        openMenu: "打开导航",
        closeMenu: "关闭导航",
        switchLanguage: "选择语言",
        theme: { light: "浅色", dark: "深色", system: "跟随系统", change: "切换主题" },
        languageChooserDetail: "文档、教程、参考与更新日志",
        onThisPage: "本页内容",
        previous: "上一篇",
        next: "下一篇",
        editPage: "编辑此页",
        updated: "更新于",
        homeEyebrow: "Pre-alpha · 面向 Cloudflare Workers 的声明式内容发布",
        homeTitle: "内容模型只定义一次，让发布契约始终一致。",
        homeDescription:
            "在 TypeScript 中声明 Collection 与 Field。Jamcaa 据此派生 D1 存储、校验、Editing Control、类型化 Entry 访问、Entry Summary、Revision 与 FTS5 迁移产物；路由和渲染仍由 Site 掌控。",
        getStarted: "运行参考 Site",
        exploreDocs: "浏览文档",
        builtWithJamcaa: "本站正在使用 Jamcaa 自身的 Page、Entry Summary、Search、Feed、Preview 与 Revision 链路。",
        architectureEyebrow: "派生契约 · 明确边界",
        architectureTitle: "一份声明，清晰的 Site 所有权。",
        architectureDescription:
            "Collection 声明驱动存储、校验、类型化访问、Entry Summary、Revision 编解码与 Search 产物。Page、路由与 Block View 保持显式；浏览器 Editing Control 位于可选的 Editor 包中。",
        latestTitle: "最新发布的文档",
        latestDescription:
            "当前 Locale 下最新发布的 Post 摘要；归档列表与 JSON Feed 共用同一套基于 Cursor 的摘要投影。",
        noPosts: "此语言暂无已发布的文档内容。",
        allPostsLoaded: "已加载全部文档内容。",
        category: "分类",
        tag: "标签",
        categoryEmpty: "此分类暂无直属文档内容。",
        tagEmpty: "暂无文档内容使用此标签。",
        searchTitle: "搜索文档",
        searchDescription: "搜索所有声明为公开的文本，并按分类或标签缩小范围。",
        searchTerms: "搜索词",
        searchPlaceholder: "搜索 Jamcaa 文档",
        allCategories: "全部分类",
        allTags: "全部标签",
        clear: "清除",
        resultsFor: "搜索结果",
        noResults: "没有匹配此搜索的文档内容。",
        enterSearch: "输入一个或多个关键词以搜索文档。",
        invalidSearchCursor: "此结果页地址无效或已过期，请重新搜索。",
        nextPage: "下一页",
        loading: "加载中…",
        loadingAnnouncement: "正在加载下一页。",
        loadedAnnouncement: (count: number, complete: boolean) =>
            complete ? `已加载 ${count} 条内容，全部内容已加载。` : `已加载 ${count} 条更多内容。`,
        loadError: "下一页未能自动加载。",
        loadErrorAnnouncement: "下一页未能自动加载，请重试或使用“下一页”链接。",
        retry: "重试",
        retrying: "正在重试…",
        pageLoaded: "页面已加载",
        notTranslatedTitle: "此页面尚未翻译。",
        notTranslatedDescription: "你可以继续阅读现有语言版本，或返回当前语言的文档首页。",
        returnHome: "返回文档首页",
        notFoundTitle: "未找到页面",
        notFoundDescription: "此地址可能已经改变，或该页面并不存在于此 Site。",
        goHome: "返回首页"
    }
} as const;

export type PublicCopy = (typeof copy)[DocsLocale];

export function publicCopy(locale: DocsLocale): PublicCopy {
    return copy[locale];
}
