import type { DocsLocale } from "./locales";

const copy = {
    "en-US": {
        languageName: "English",
        skipToContent: "Skip to content",
        navigationLabel: "Primary navigation",
        productName: "Jamcaa Docs",
        docs: "Docs",
        guides: "Guides",
        reference: "Reference",
        changelog: "Changelog",
        search: "Search",
        dashboard: "Console",
        openMenu: "Open navigation",
        closeMenu: "Close navigation",
        switchLanguage: "Choose language",
        theme: { light: "Light", dark: "Dark", system: "System", change: "Change theme" },
        languageChooserDetail: "Product overview, quick start, guides, API reference, and changelog",
        docsNavigation: "Documentation navigation",
        expandSection: (label: string) => `Expand ${label}`,
        collapseSection: (label: string) => `Collapse ${label}`,
        onThisPage: "On this page",
        previous: "Previous",
        next: "Next",
        editPage: "Edit this page",
        updated: "Updated",
        homeEyebrow: "Content publishing for Cloudflare Workers · Pre-alpha",
        homeTitle: "Define content once, then carry it all the way to publishing.",
        homeDescription:
            "Jamcaa lets a Site define Collections and Fields in TypeScript, then connects D1 storage, validation, Editing Controls, typed reads and writes, Revisions, and full-text Search. Routes and presentation remain yours.",
        getStarted: "Run it locally",
        exploreDocs: "See how it works",
        builtWithJamcaa: "This Site runs on Jamcaa and continuously exercises its real documentation workflow.",
        architectureEyebrow: "From declaration to publishing",
        architectureTitle: "Automate what must agree. Keep product decisions in the Site.",
        architectureDescription:
            "The Platform owns reusable content contracts. Each Site owns routes, page structure, presentation, and product policy. That boundary removes repeated synchronization work without turning Jamcaa into a page generator.",
        latestTitle: "Recently updated",
        latestDescription: "Browse the latest documentation published in this language.",
        noPosts: "No documentation has been published in this language yet.",
        allPostsLoaded: "You have reached the end of the documentation.",
        category: "Category",
        tag: "Tag",
        categoryEmpty: "No documentation is assigned directly to this category.",
        tagEmpty: "No documentation uses this tag.",
        searchTitle: "Search Jamcaa Docs",
        searchDescription: "Search published text, then narrow the results by category or tag.",
        searchTerms: "Keywords",
        searchPlaceholder: "Search Jamcaa Docs",
        allCategories: "All categories",
        allTags: "All tags",
        clear: "Clear",
        resultsFor: "Results for",
        noResults: "No documentation matches these keywords.",
        enterSearch: "Enter one or more keywords to search the documentation.",
        invalidSearchCursor: "This results page is no longer valid. Start the search again.",
        nextPage: "Next page",
        loading: "Loading…",
        loadingAnnouncement: "Loading the next page.",
        loadedAnnouncement: (count: number, complete: boolean) =>
            complete ?
                count === 0 ?
                    "You have reached the end of the documentation."
                :   `${count} more ${count === 1 ? "item" : "items"} loaded. You have reached the end of the documentation.`
            :   `${count} more ${count === 1 ? "item" : "items"} loaded.`,
        loadError: "The next page did not load automatically.",
        loadErrorAnnouncement: "The next page did not load automatically. Retry or use the Next page link.",
        retry: "Retry",
        retrying: "Retrying…",
        pageLoaded: "Page loaded",
        notTranslatedTitle: "This page is not available in English yet.",
        notTranslatedDescription: "Continue in an available language, or return to the English documentation home.",
        returnHome: "Return to docs home",
        notFoundTitle: "Page not found",
        notFoundDescription: "The address may have changed, or this page may no longer exist.",
        goHome: "Go home"
    },
    "zh-Hans-CN": {
        languageName: "简体中文",
        skipToContent: "跳到正文",
        navigationLabel: "主导航",
        productName: "Jamcaa 文档",
        docs: "文档",
        guides: "指南",
        reference: "参考",
        changelog: "更新日志",
        search: "搜索",
        dashboard: "控制台",
        openMenu: "打开导航",
        closeMenu: "关闭导航",
        switchLanguage: "选择语言",
        theme: { light: "浅色", dark: "深色", system: "跟随系统", change: "切换主题" },
        languageChooserDetail: "产品概览、快速开始、教程、API 参考与更新日志",
        docsNavigation: "文档目录",
        expandSection: (label: string) => `展开“${label}”目录`,
        collapseSection: (label: string) => `收起“${label}”目录`,
        onThisPage: "本页内容",
        previous: "上一篇",
        next: "下一篇",
        editPage: "编辑此页",
        updated: "更新于",
        homeEyebrow: "面向 Cloudflare Workers 的内容发布 Platform · Pre-alpha",
        homeTitle: "用一份内容声明，搭好从编辑到发布的整条链路。",
        homeDescription:
            "Jamcaa 让 Site 用 TypeScript 定义 Collection 与 Field，再自动衔接 D1 存储、数据校验、Editing Control、类型安全读写、Revision 与全文 Search；路由和页面呈现仍由你掌控。",
        getStarted: "开始本地运行",
        exploreDocs: "了解工作方式",
        builtWithJamcaa: "这个 Site 就运行在 Jamcaa 上，并持续用真实文档流程验证它。",
        architectureEyebrow: "从声明到发布",
        architectureTitle: "让必须一致的部分自动一致，把产品决定留给 Site。",
        architectureDescription:
            "Platform 负责可复用的内容契约，Site 负责路由、页面结构、视觉与业务策略。边界清楚后，就不必在数据库、表单、类型和搜索之间反复手动同步。",
        latestTitle: "最近更新",
        latestDescription: "查看当前语言下最近发布或更新的文档。",
        noPosts: "当前语言还没有已发布的文档。",
        allPostsLoaded: "已经看到全部文档。",
        category: "分类",
        tag: "标签",
        categoryEmpty: "这个分类下还没有直接归属的文档。",
        tagEmpty: "还没有文档使用这个标签。",
        searchTitle: "搜索 Jamcaa 文档",
        searchDescription: "搜索已发布的正文，再用分类或标签缩小结果范围。",
        searchTerms: "关键词",
        searchPlaceholder: "搜索 Jamcaa 文档",
        allCategories: "全部分类",
        allTags: "全部标签",
        clear: "清除",
        resultsFor: "搜索结果",
        noResults: "没有找到匹配这些关键词的文档。",
        enterSearch: "输入一个或多个关键词开始搜索。",
        invalidSearchCursor: "这个结果页已经失效，请重新搜索。",
        nextPage: "下一页",
        loading: "加载中…",
        loadingAnnouncement: "正在加载下一页。",
        loadedAnnouncement: (count: number, complete: boolean) =>
            complete ?
                count === 0 ?
                    "已经看到全部文档。"
                :   `又加载了 ${count} 条内容，已经看到全部文档。`
            :   `又加载了 ${count} 条内容。`,
        loadError: "下一页没有自动加载成功。",
        loadErrorAnnouncement: "下一页没有自动加载成功，请重试或使用“下一页”链接。",
        retry: "重试",
        retrying: "正在重试…",
        pageLoaded: "页面已加载",
        notTranslatedTitle: "这个页面暂时没有简体中文版。",
        notTranslatedDescription: "你可以继续阅读已有语言版本，或返回简体中文文档首页。",
        returnHome: "返回文档首页",
        notFoundTitle: "未找到页面",
        notFoundDescription: "这个地址可能已经改变，或页面已经不存在。",
        goHome: "返回首页"
    }
} as const;

export type PublicCopy = (typeof copy)[DocsLocale];

export function publicCopy(locale: DocsLocale): PublicCopy {
    return copy[locale];
}
