import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { expect, it } from "vitest";
import { blockPlainText } from "@jamcaaxian/core/content";
import { siteBlockRegistry } from "../src/content/site-blocks";
import { docsSeedPosts, productHomePages } from "./migrate-docs-content";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const outputPath = path.join(root, "apps/docs/.wrangler/docs-migration.sql");

function sqlString(value: string): string {
    return `'${value.replaceAll("'", "''")}'`;
}

/** One stable UUID per slug so the generated SQL is deterministic. */
function postId(slug: string): string {
    const hex = createHash("sha1").update(`jamcaa-docs:${slug}`).digest("hex").slice(0, 32);

    return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

const now = "(cast(unixepoch('subsecond') * 1000 as integer))";

async function readDocsRecord(): Promise<Record<string, string>> {
    const record: Record<string, string> = {};

    for (const file of ["CONTEXT.md", "README.md"]) {
        record[file] = await readFile(path.join(root, file), "utf8");
    }

    for (const folder of ["docs/adr", "docs/agents"]) {
        for (const name of await readdir(path.join(root, folder))) {
            record[`${folder}/${name}`] = await readFile(path.join(root, folder, name), "utf8");
        }
    }

    return record;
}

it("writes the repository docs migration SQL", async () => {
    const posts = docsSeedPosts(await readDocsRecord());
    const pages = productHomePages();

    expect(posts.length).toBeGreaterThan(25);
    expect(pages).toHaveLength(2);

    const statements = [
        "-- Generated by scripts/generate-docs-migration-sql.ts. Do not edit by hand.",
        `INSERT OR IGNORE INTO user (id, name, email, email_verified, image, created_at, updated_at) `
            + `VALUES ('docs-author', 'Documentation', 'docs@jamcaa.local', 1, NULL, ${now}, ${now});`,
        `INSERT OR IGNORE INTO category (id, name, slug, parent_id, created_at, updated_at) `
            + `VALUES ('docs-category', 'Documentation', 'documentation', NULL, ${now}, ${now});`,
        "DELETE FROM post WHERE translation_id = 'product:home';",
        ...pages.map(page => {
            const id = postId(`page:${page.locale}:${page.address}`);

            return (
                `INSERT INTO page (id, locale, translation_id, title, address, body, status, created_at, updated_at) `
                + `VALUES (${sqlString(id)}, ${sqlString(page.locale)}, ${sqlString(page.translationId)}, `
                + `${sqlString(page.title)}, ${sqlString(page.address)}, ${sqlString(JSON.stringify(page.body))}, `
                + `'published', ${now}, ${now}) `
                + `ON CONFLICT(locale, address) DO UPDATE SET translation_id = excluded.translation_id, `
                + `title = excluded.title, body = excluded.body, status = excluded.status, updated_at = excluded.updated_at;`
            );
        }),
        ...posts.map(post => {
            const id = postId(`${post.locale}:${post.slug}`);
            const bodyValue = JSON.stringify(post.body);
            const bodyPlain = blockPlainText(post.body, siteBlockRegistry);

            return (
                `INSERT INTO post (id, slug, locale, translation_id, status, author_id, category_id, created_at, updated_at, published_at, title, excerpt, "body__value", "body__plain") `
                + `VALUES (${sqlString(id)}, ${sqlString(post.slug)}, ${sqlString(post.locale)}, ${sqlString(post.translationId)}, 'published', `
                + `'docs-author', 'docs-category', ${now}, ${now}, ${now}, `
                + `${sqlString(post.title)}, ${sqlString(post.excerpt)}, ${sqlString(bodyValue)}, ${sqlString(bodyPlain)}) `
                + `ON CONFLICT(locale, slug) DO UPDATE SET translation_id = excluded.translation_id, title = excluded.title, `
                + `excerpt = excluded.excerpt, "body__value" = excluded."body__value", `
                + `"body__plain" = excluded."body__plain", updated_at = excluded.updated_at;`
            );
        }),
        ""
    ];
    const sql = statements.join("\n");

    expect(sql).toContain('"body__value"');
    expect(sql).toContain('"body__plain"');
    expect(sql).toContain("INSERT INTO page");
    expect(sql).toContain("DELETE FROM post WHERE translation_id = 'product:home'");
    expect(sql).not.toContain(", body) VALUES");
    expect(sql).not.toContain("excerpt = excluded.excerpt, body = excluded.body");

    await mkdir(path.dirname(outputPath), { recursive: true });
    await writeFile(outputPath, sql, "utf8");
}, 30_000);
