import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { expect, it } from "vitest";
import { repositoryPosts } from "./migrate-docs-content";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const outputPath = path.join(root, "apps/docs/.wrangler/docs-migration.sql");

function sqlString(value: string): string {
    return `'${value.replaceAll("'", "''")}'`;
}

/** One stable UUID per slug so the generated SQL is deterministic. */
function postId(slug: string): string {
    const hex = createHash("sha1").update(`jamcaa-docs:${slug}`).digest("hex").slice(0, 32);

    return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

const now = "(cast(unixepoch('subsecond') * 1000 as integer))";

async function readDocsRecord(): Promise<Record<string, string>> {
    const record: Record<string, string> = {};

    for (const file of ["CONTEXT.md", "README.md"]) {
        record[file] = await readFile(path.join(root, file), "utf8");
    }

    for (const folder of ["docs/adr", "docs/agents"]) {
        for (const name of await readdir(path.join(root, folder))) {
            record[`${folder}/${name}`] = await readFile(path.join(root, folder, name), "utf8");
        }
    }

    return record;
}

it("writes the repository docs migration SQL", async () => {
    const posts = repositoryPosts(await readDocsRecord());

    expect(posts.length).toBeGreaterThan(25);

    const statements = [
        "-- Generated by scripts/generate-docs-migration-sql.ts. Do not edit by hand.",
        `INSERT OR IGNORE INTO user (id, name, email, email_verified, image, created_at, updated_at) `
            + `VALUES ('docs-author', 'Documentation', 'docs@jamcaa.local', 1, NULL, ${now}, ${now});`,
        `INSERT OR IGNORE INTO category (id, name, slug, parent_id, created_at, updated_at) `
            + `VALUES ('docs-category', 'Documentation', 'documentation', NULL, ${now}, ${now});`,
        ...posts.map(
            post =>
                `INSERT INTO post (id, slug, status, author_id, category_id, created_at, updated_at, published_at, title, excerpt, body) `
                + `VALUES (${sqlString(postId(post.slug))}, ${sqlString(post.slug)}, 'published', `
                + `'docs-author', 'docs-category', ${now}, ${now}, ${now}, `
                + `${sqlString(post.title)}, ${sqlString(post.excerpt)}, ${sqlString(JSON.stringify(post.body))}) `
                + `ON CONFLICT(slug) DO UPDATE SET title = excluded.title, excerpt = excluded.excerpt, `
                + `body = excluded.body, updated_at = excluded.updated_at;`
        ),
        ""
    ];

    await mkdir(path.dirname(outputPath), { recursive: true });
    await writeFile(outputPath, statements.join("\n"), "utf8");
}, 30_000);
